### ISSUE TITLE
Update bundle size optimization for Blueprint Icons

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-dev-utils#44]
Reviewing a recent bundle treemap on our Toolbox app, it looks like the big Blueprint icons package has returned and is taking up a lot of space again.  My bet is that something about the path changed, and the workaround we implemented in #25 a while back needs to be updated.

<img width="2168" alt="Screenshot 2023-05-23 at 8 11 51 PM" src="https://github.com/xh/hoist-dev-utils/assets/225806/622c8d52-1005-4034-8cbd-ffc18f743b80">

**Comment by amcclain** [comment]
@cnrudd if you have a chance to review - we could look together tomorrow as I'd like to cut a dev-utils release with an even bigger fix to FontAwesome icons.

**Comment by cnrudd** [comment]
This has been fixed in the following hoist-react and hoist-dev-utils branches:
https://github.com/xh/hoist-react/commits/bpIcons
https://github.com/xh/hoist-dev-utils/tree/bpIcons

and can be tested easily in toolbox branch `bpIcons`.

Unfortunately this is a breaking change in hoist-dev-utils which will require apps to switch the new versions of hoist-react and hoist-dev-utils at the same time because BP4 brought in a requirement for using a new method for getting the icon name.

(See https://github.com/palantir/blueprint/issues/2193#issuecomment-1204741102 for more details)

The path to the icons is fixed in hoist-dev-utils and the new method is added in the requireBlueprintIcons.js file hoist-react.

I have committed some temporary changes to the package.json files in the `bpIcons` branches that load hoist-dev-utils and hoist-react from specific commits.  These make it much easier to run the project and to do bundle analysis.

Once the hoist-dev-utils branch is merged and release, we can update the lib version to the new release in hoist-react before merging it in.

![image](https://github.com/xh/hoist-dev-utils/assets/2573928/1e2785ea-d008-4a3b-99d7-2cb65948f105)
